#!/bin/bash
set -euax

EXPNAM=$1
PDY=$2
cyc=$3
COMROT=${4:-$STMP/$USER}
ARCDIR=${5:-$COMROT/archive}
TMPDIR=${6:-$STMP/$USER/tmpdir}

ACCOUNT=${ACCOUNT:-CFS-T2O}
CUE2RUN=${CUE2RUN:-dev}
KEEPDATA=${KEEPDATA:-NO}

vday=${PDY}
vcyc=${cyc}

echo -------------------------------------------------------------------------------------------------------------------
echo Starting the runfits for:
echo -------------------------------------------------------------------------------------------------------------------
echo "EXPNAM    " $EXPNAM       # argument 1 - experiment name    - required  (can be prod in which case COMROT is moot)
echo "PDY       " $PDY          # argument 2 - date of validation - required
echo "cyc       " $cyc          # argument 3 - cycle of validation - required
echo "COMROT    " $COMROT       # argument 4 - COMROT directory   - optional - defaults to /stmp/$USER
echo "ARCDIR    " $ARCDIR       # argument 5 - ARCDIR directory   - optional - defaults to $COMROT/archive
echo "TMPDIR    " $TMPDIR       # argument 6 - TMPDIR directory   - optional - defaults to /stmp/$USER/tmpdir
echo "ACCOUNT   " $ACCOUNT      # inherited  - project code       - required - defaults to nothing
echo "KEEPDATA  " $KEEPDATA     # inherited  - retain rundir      - optional - defaults to NO (rmdir)
echo -------------------------------------------------------------------------------------------------------------------

fitdir=${fitdir:-$(dirname $0)}; fitdir=$(cd $fitdir; pwd)
LOGDIR=${LOGDIR:-$COMROT/logs/${PDY}${cyc}}

set -euax          

vrfytmpdiris=$TMPDIR
unset TMPDIR

cat<<EOF | sbatch
#!/bin/bash
#SBATCH --job-name=FITS.$EXPNAM.$PDY$cyc --time=00:20:00
#SBATCH --nodes=3 --ntasks-per-node=1
#SBATCH --mem=128G
#SBATCH --output=$LOGDIR/hera.fit2obs.log.$$
#SBATCH --account=$ACCOUNT  
#SBATCH --qos=batch 

set -euax

set +x
module use /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/modulefiles/stack
module load  hpc/1.1.0  hpc-intel/2022.1.2  hpc-impi/2022.1.2
module load netcdf/4.7.0
module list
set -x

export OMP_NUM_THREADS=${FITOMP:-1}
export MPIRUN="srun --export=ALL -n 3"

export EXP=$EXPNAM
export COMPONENT=${COMPONENT:-atmos}
export COMIN=$ROTDIR
export KEEPDATA=$KEEPDATA

export fitdir=$fitdir
export ARCDIR=$ARCDIR
export TMPDIR=$vrfytmpdiris
export ACPROFit=${ACPROFit:-YES}
export NEMS=${NEMS:-YES}   

time $fitdir/runfits $EXPNAM $PDY $cyc $COMROT

EOF
